# Generated by Django 4.0.5 on 2022-06-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stage6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
