# Generated by Django 4.0.5 on 2022-06-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stage6', '0002_alter_people_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='id',
            new_name='people_id',
        ),
    ]
