# Generated by Django 4.0.5 on 2022-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stage6', '0003_rename_id_people_people_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='people_id',
        ),
        migrations.AddField(
            model_name='people',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
